### ISSUE TITLE
[Feature] Toggle switch to turn off and on.

### ISSUE THREAD

**Issue by darkRaspberry** [ephraimduncan/minimal-youtube#2]
App is good, Home is disabled, recommendation is gone, comments gone, No distraction.

I think there should be any toggle switch which can quickly turn it off and on. Sometime I still want to watch those recommendation when I'm bored.

What can be done!
 - A simple toggle switch like other apps implemented, nothing fancy just simple button. Example attached below.
 - A keyboard shortcuts can can quickly toggle the state like other app implemented. Can be found here on chromium browser. `chrome://extensions/shortcuts`

![Screenshot from 2022-10-01 19-04-50](https://user-images.githubusercontent.com/56693429/193412250-9eedd249-466e-4845-a557-2613712f07b4.jpg)

**Comment by dephraiim** [comment]
This is great. I'll add it later but if you want to submit a PR, I'm ready to review and merge it.

**Comment by darkRaspberry** [comment]
I don't know anything about extension but I will try.

**Comment by dephraiim** [comment]
Okay. I am working on it too

**Comment by TheAnachronism** [comment]
Really hope this gets implemented. A single shortcut to quickly switch between the two views.

**Comment by AradhanaChhabra** [comment]
hey @dephraiim  I loved your extension and even I was thinking of this toggle while using and then found this issue. I would like to work on it as well!

**Comment by dephraiim** [comment]
@AradhanaChhabra I am working on it at the moment. You could join me

**Comment by AradhanaChhabra** [comment]
> @AradhanaChhabra I am working on it at the moment. You could join me

Sure. Please let me know how can I get started.

**Comment by MatheusR42** [comment]
Hello @darkRaspberry , @ephraimduncan , @TheAnachronism and @AradhanaChhabra ! 

Maybe I am a little bit late, but I created this feature here :smile: :
https://github.com/ephraimduncan/minimal-youtube/pull/33

I hope you enjoy! If you have any suggestions feel free to add a comment in the PR

**Comment by ephraimduncan** [comment]
Closing this as this is currently on the repo, yet to push to the chrome web store
