### ISSUE TITLE
Comments are not always distraction

### ISSUE THREAD

**Issue by bst1n** [ephraimduncan/minimal-youtube#21]
Not being able to read comments prevent me from using the extension

**Comment by dephraiim** [comment]
@bvairet I have a workaround. I'll forward it to you

**Comment by YKoas** [comment]
I also would love a way to get comments back as well as I enjoy that "community feel"

**Comment by toprak** [comment]
updates on it?

**Comment by ephraimduncan** [comment]
Comments are now enabled.

**Comment by bst1n** [comment]
> enabled

does not work

**Comment by ephraimduncan** [comment]
I've submitted it to the chrome web store, it is currently pending review. In the mean time, you can manually download the assets and add it to chrome with the steps in the readme

**Comment by lephantriduc** [comment]
1.2.1 version is not showing comments! I got it straight from Firefox addons store.
