### ISSUE TITLE
Playlist page alignment is not correct.

### ISSUE THREAD

**Issue by Sidheeqpallam** [ephraimduncan/minimal-youtube#30]
The playlist is not aligned properly, it is look like this: 
![playlist](https://github.com/dephraiim/minimal-youtube/assets/103623147/77854f6a-2a13-4e6b-b1e5-b37e4275a322)

The two containers are overlapped.

**Comment by MatheusR42** [comment]
Hi @Sidheeqpallam and @ephraimduncan , I created this pull request to solve this issue:
https://github.com/ephraimduncan/minimal-youtube/pull/34

If you have any suggestions feel free to add comments. Thanks!

**Comment by ephraimduncan** [comment]
The PR has been merged❤️
