### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by HeroBaga** [ephraimduncan/minimal-youtube#36]
Any youtube pages go to Infinite loading. Firefox and Chrome same bug. The page loaded I can use picture-in-picture mode to play the video
![image](https://github.com/ephraimduncan/minimal-youtube/assets/36224434/d5e3ce03-f455-42f5-b9b4-13e05e0c854d)

**Comment by Flmstr** [comment]
Good afternoon, same problem =(

**Comment by MatheusR42** [comment]
hi @Flmstr @dstark and @HeroBaga , when I download the extension from github and load the extesion following this guide it works:
https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

I think its only needed to update in firefox store

**Comment by dstark** [comment]
> I think its only needed to update in firefox store

@MatheusR42, thanks so much for the pointer. The latest release on GitHub appears to be 1.1.0, and that's also now the most current one in the Firefox repository and the version I have installed. But I'm still getting the "infinite loading" behavior (Windows 10, Firefox 126).

**Comment by cameron-toy** [comment]
I'm also getting this issue

Firefox 126.0.1
Extension 1.1.0 installed from store

**Comment by ephraimduncan** [comment]
I  have pushed an update, v1.2.1 with a fix to this to the Mozilla Store and the Chrome Store. Mozilla has been approved, I'm waiting for Chrome. 

Let me know if the issue still persists else I'll go ahead and close the issue

**Comment by HeroBaga** [comment]
Checked for Mozilla, works fine
